import 'bootstrap/dist/css/bootstrap.min.css';
import Head from 'next/head';
import MainPage from './MainPage';

export default function Home() {
 
return (
<>
  <Head>
    <title>Parent Updater</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
    {/* <link rel="preconnect" href="https://rsms.me/" />
    <link rel="stylesheet" href="https://rsms.me/inter/inter.css" /> */}
  </Head>


  <MainPage/>

</>
)
}